### ISSUE TITLE
Can't install the package

### ISSUE THREAD

**Issue by onfqzmpgvr** [wearejust/laravel-amp#1]
Because this package is in branch dev-master, So it can't be installed nomally. 

```
[InvalidArgumentException]
  Could not find package wearejust/laravel-amp at any version for your minimum-stability (stable). Check the package
  spelling or your minimum-stability
```

And when i typed `php artisan vendor:publish ` it displayed 

```
[Just\Amp\Exceptions\AmpRouteActionMustBeArray]
  Action for route [] must be an array
```

In your usage intrucstion, i was confusing in 

`In your view, include the amp::tag file. This will match the AMP route (if exists) and put an link to the amp content in your HTML`

**Comment by ceesvanegmond** [comment]
@onfqzmpgvr 
Because this package is in branch dev-master, So it can't be installed nomally.
>> That's right! I'ts not final yet.

Could you share some code please? Ideas to make the docs better?

**Comment by iscmafm** [comment]
@onfqzmpgvr Hi! you need to add into your composer.json project of laravel the next line:

> composer.json project
`"minimum-stability":"dev"`

Then you can run: 
`composer require wearejust/laravel-amp`

On tag.twig I remplace this: 

```
 {% if hasAmpUrl %}
    <link rel="amphtml" href="{{ ampUrl }}">
{% endif %}
```

For this twig.blade.php: 

```
  @if ( $hasAmpUrl )
     <link rel="amphtml" href="{{ $ampUrl }}">
 @endif
```

Good luck!

**Comment by facundofarias** [comment]
Uops! I've suffered exactly the same thing. Can you please add it to the docs?
Thanks!
