### ISSUE TITLE
Config file is not being published

### ISSUE THREAD

**Issue by facundofarias** [wearejust/laravel-amp#2]
[amp.php](https://github.com/wearejust/laravel-amp/blob/master/config/amp.php) file is not being published when I run:

`php artisan vendor:publish`

Thanks.

**Comment by guncebektas** [comment]
did u add?

`// app.php
'providers' => [
    ...
    Just\Amp\Laravel\AmpServiceProvider::class,
],
'aliases' => [
    ...
    'AmpRouter' => Just\Amp\Laravel\AmpRouteFacade::class,
]`

**Comment by johnhout** [comment]
Nope add pulk request 👍
