### ISSUE TITLE
hasAmpUrl and ampUrl variables not getting defined

### ISSUE THREAD

**Issue by ricardo** [wearejust/laravel-amp#7]
I'm using blade instead of twig, so I wanted to check the variables hasAmpUrl and ampUrl, but they don't seen to get defined by opening an amp route view with dd(get_defined_vars()).

**Comment by pkarastelev** [comment]
Since you are using blade, you should publish the view with `php artisan vendor:publish --tag=views`

Then you have to edit the view in your `resources/views/vendor/amp` folder to use the blade syntax:
```
@if($hasAmpUrl)
    <link rel="amphtml" href="{{ $ampUrl }}">
@endif
```

**Comment by williamnwogbo** [comment]
@pkarastelev I am struggling to grasp the documentation, if you can assist me I will really appreciate, I have a blog with at least 2 million page views daily, it was built with Laravel. I have done all the installation but amp aint working, and this line isnt clear **"There well be two routes registered. One with '/url-of-my-route', and one prefixed with the config value you specify in the config file such as googleamp. The logic for both routes is the same, but the view that's being rendered for the amp route affixed the the config value you specify in the config file (view-affix). In your view, include the amp::tag file. This will match the AMP route (if exists) and put an link to the amp content in your HTML."**

**Comment by pkarastelev** [comment]
@williamnwogbo First of all you have to publish the config. Use `php artisan vendor:publish --tag=config`.
After this you will have a `amp.php` in your config folder. In this config file you can define your prefix.
`'prefix' => 'mobile',`
In this case, if you have registered a route with the `Route::amp(...)` syntax, there will be registered two routes, which both use the same Controller. 
`Route::amp('test', ['as' => 'test-amp', 'uses' => 'TestController@test']);`
the registered routes are:

- app.dev/test (desktop version)
- app.dev/mobile/test (amp version)

Now you should have two blade files. One is your standard desktop View (test.blade.php)
and the other one should have the affix which is defined in your `config/amp.php`.

`'view-affix' => '-amp',`
So your AMP-view should be called `test-amp.blade.php`)
Your Controller just has to return the default view of the desktop version (`test.blade.php`).
