### ISSUE TITLE
Non-static method 

### ISSUE THREAD

**Issue by vdeshan** [wearejust/laravel-amp#8]
Non-static method 
Just\Amp\Laravel\AmpRouter::registerMacros() should not be called statically

`use` Just\Amp\Laravel\AmpRouter;`

  `public function boot() {`
        //
       `AmpRouter::registerMacros();`
        `parent::boot();`
   ` }`

Thats my code

**Comment by shebinleo** [comment]
@vdeshan follow the Installation instructions. Add `AmpRouter ` aliases and use it.

**Comment by pkarastelev** [comment]
@vdeshan I might be late, but for those who can't get it to work, too:
You have to use the facade:
`use Just\Amp\Laravel\AmpRouteFacade;`

And then:
`AmpRouteFacade::registerMacros();`
`parent::boot();`
